homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 869
  unit_system: imperial
  time_zone: America/Chicago
  whitelist_external_dirs:
    - /tmp

  packages: !include_dir_named packages
  customize: !include_dir_merge_named customize

alarm_control_panel:
  - platform: arlo
    home_mode_name: 'Home'

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

automation: !include_dir_merge_list automation

binary_sensor: !include_dir_merge_list binary_sensors

camera:
  - platform: arlo
  - platform: generic
    name: Derek's Location
    still_image_url: !secret derek_map_url
    limit_refetch_to_url_change: true
  - platform: generic
    name: Kari's Location
    still_image_url: !secret kari_map_url
    limit_refetch_to_url_change: true

# lutron_caseta:
#     host: !secret lutron_host_ip
#     keyfile: certs/caseta.key
#     certfile: certs/caseta.crt
#     ca_certs: certs/caseta-bridge.crt

lutron_caseta_pro:
  bridges:
    - host: !secret lutron_host_ip
      mac: !secret lutron_mac
      switch: [9, 16]

# Enable Home Assistant Cloud (for voice control)
cloud: !include_dir_merge_named cloud

# Enables configuration UI
config:

cover:
  - platform: myq
    type: liftmaster
    username: !secret myq_username
    password: !secret myq_password

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

device_tracker:
  # - platform: automatic
  #   client_id: !secret automatic_client_id
  #   secret: !secret automatic_secret
  #   current_location: false
  - platform: nmap_tracker
    hosts: 192.168.86.0/24
    exclude: !secret nmap_exclusions

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv # home assistant wakes up the apple tv when it connects... causing the TV to turn on

# Enables the frontend
frontend:

group: !include_dir_merge_named groups

# Enables support for tracking state changes over time
history:

homekit: !include homekit.yaml

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

hue:
  bridges:
    - host: !secret hue_host_ip

input_boolean:
  guest_mode:
    # This prevents certain automations from executing.
    # e.g. turning everything off on our guests if we leave
    name: Guest mode
    initial: off
    icon: mdi:nature-people

# Show links to resources in log and frontend
# introduction:

life360:
  accounts:
    username: !secret life360_username
    password: !secret life360_password

# View all events in a logbook
logbook:

# Display a map on the frontend
map:

media_player:
  - platform: plex
  # - platform: samsungtv
  #   host: !secret samsung_tv_host_ip
  #   mac: !secret samsung_tv_mac_address
  #   port: 8001
  #   name: Living Room TV

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_secret

notify:
  - name: facebook
    platform: facebook
    page_access_token: !secret facebook_token
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

nuheat:
  username: !secret nuheat_username
  password: !secret nuheat_password
  devices: !secret nuheat_thermostat

person:
  - name: Derek
    id: broox
    user_id: !secret user_id_broox
    device_trackers:
      - device_tracker.life360_derek_brooks
  - name: Kari
    id: kbroox
    user_id: !secret user_id_kbroox
    device_trackers:
      - device_tracker.life360_kari

# Make sure to purge the history to keep the DB reasonably sized.
recorder:
  purge_interval: 1
  purge_keep_days: 14
  exclude:
    domains:
      - automation

ring:
  username: !secret ring_username
  password: !secret ring_password

scene: !include_dir_merge_list scenes

script: !include_dir_merge_named scripts

sensor: !include_dir_merge_list sensors

switch: !include_dir_merge_list switches


# Track the sun
sun:

system_health:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Check for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: tru

zwave:
  usb_path: /dev/ttyUSB0

zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 150
  icon: mdi:home

zone 2:
  name: Gravitate
  latitude: !secret gravitate_latitude
  longitude: !secret gravitate_longitude
  icon: mdi:laptop
  radius: 100  # meters

zone 3:
  name: Carver
  latitude: !secret carver_latitude
  longitude: !secret carver_longitude
  icon: mdi:school
  radius: 200  # meters

zone 4:
  name: Moulton
  latitude: !secret moulton_latitude
  longitude: !secret moulton_longitude
  icon: mdi:school
  radius: 300  # meters

zone 5:
  name: YMCA
  latitude: !secret ymca_latitude
  longitude: !secret ymca_longitude
  radius: 120  # meters
  icon: mdi:dumbbell

zone 6:
  name: Yoga
  latitude: !secret powerlife_latitude
  longitude: !secret powerlife_longitude
  radius: 120
  icon: mdi:dumbbell

zone 7:
  name: Pool
  latitude: !secret pool_latitude
  longitude: !secret pool_longitude
  radius: 120
  icon: mdi:swim
