homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 869
  unit_system: imperial
  time_zone: America/Chicago
  whitelist_external_dirs:
    - /tmp

  packages: !include_dir_named packages
  customize:
    climate.master_bath:
      friendly_name: Bathroom floor
    cover.garage_door_opener:
      friendly_name: Garage door
    group.stairwell:
      icon: mdi:stairs
    group.turntable_lights:
      icon: mdi:album
    light.cabinets:
      friendly_name: Cabinet accents
    light.fridge_lights:
      friendly_name: Fridge accents
    light.great_room:
      friendly_name: Great room Hue bulbs
    light.guest_bedroom:
      friendly_name: Guest bedroom Hue bulbs
    light.guest_office:
      friendly_name: Guest office Hue bulbs
    light.kitchen:
      friendly_name: Kitchen Hue bulbs
    light.lamp_dimmer_one_level:
      friendly_name: Blinky
      icon: mdi:ghost
    light.lamp_dimmer_two_level:
      friendly_name: Christmas tree
      icon: mdi:pine-tree
    light.master_bedroom:
      friendly_name: Master bedroom Hue bulbs
    light.office:
      friendly_name: Office Hue bulbs
    light.rec_room:
      friendly_name: Rec room Hue bulbs
    light.stairwell:
      friendly_name: Stairwell Hue bulbs
    light.turntable:
      friendly_name: Turntable Hue bulbs
    media_player.samsung_tv_un60ks8000:
      friendly_name: Samsung TV
      initial_state: off
      start_off: true
      # hidden: true
    media_player.kitchen_home:
      friendly_name: Google Home
      icon: mdi:google-assistant
    sensor.entryway_thermostat_temperature:
      friendly_name: Inside temp
    sensor.entryway_thermostat_humidity:
      friendly_name: Inside humidity
    sensor.dark_sky_apparent_temperature:
      friendly_name: Feels like
    sensor.dark_sky_cloud_coverage:
      friendly_name: Cloud coverage
    sensor.dark_sky_summary:
      friendly_name: Conditions
    sensor.dark_sky_temperature:
      friendly_name: Outside temp
    switch.couch_ge_12721_switch:
      friendly_name: Couch lamp
      icon: mdi:lightbulb
    switch.driveway_light:
      icon: mdi:lightbulb
    switch.office_ge_12721_switch:
      friendly_name: Miffy
      icon: mdi:lightbulb
    zwave.couch_ge_12721:
      friendly_name: Couch outlet
    zwave.office_ge_12721:
      friendly_name: Office outlet

alarm_control_panel:
  - platform: arlo
    home_mode_name: 'Home'

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

automation: !include_dir_merge_list automation

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

camera:
  - platform: arlo
  - platform: generic
    name: Derek's Location
    still_image_url: !secret derek_map_url
    limit_refetch_to_url_change: true
  - platform: generic
    name: Kari's Location
    still_image_url: !secret kari_map_url
    limit_refetch_to_url_change: true

# These IDs come from the JSON file that the Lutron app's "Send Integration Report"
# option delivers. That file needs to be saved as ./caseta_[lutron_host_ip].json
caseta:
  bridges:
  - host: !secret lutron_host_ip
    devices:
      - id: 2
        type: dimmer
      - id: 3
        type: remote
      - id: 4  # BR Pico
        type: remote
      - id: 5  # Foyer
        type: dimmer
      - id: 6  # Foyer Pico
        type: remote
      - id: 7  # LR Ceiling lamp
        type: dimmer
      - id: 8  # Front porch
        type: dimmer
      - id: 9  # driveway
        type: switch
      - id: 10  # lounge
        type: dimmer
      - id: 11  # lounge pico
        type: remote
      - id: 12  # mudroom lounge pico
        type: remote
      - id: 13  # kitchen dimmer
        type: dimmer
      - id: 14  # kitchen pico
        type: remote

# Enable Home Assistant Cloud
cloud:
  alexa:
    filter:
      exclude_domains:
        - alert
        - automation
        - lock
        - media_player
        - script
      exclude_entities:
        - group.all_automations
        - group.all_devices
        - group.batteries
        - group.cameras
        - group.default_view
        - group.exterior_climate
        - group.google_homes
        - group.hass
        - group.interior_climate
        - group.maps
        - group.modes
        - group.scenes
        - group.signal
        - group.sonos
        - group.status

# Enables configuration UI
config:

cover:
  - platform: myq
    type: liftmaster
    username: !secret myq_username
    password: !secret myq_password

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

device_tracker:
  # - platform: automatic
  #   client_id: !secret automatic_client_id
  #   secret: !secret automatic_secret
  #   current_location: false
  - platform: nmap_tracker
    hosts: 192.168.86.0/24
    exclude: !secret nmap_exclusions
  - platform: owntracks
    max_gps_accuracy: 200

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv # home assistant wakes up the apple tv when it connects... causing the TV to turn on

# Enables the frontend
frontend:

group: !include_dir_merge_named groups

# Enables support for tracking state changes over time
history:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

hue:
  bridges:
    - host: !secret hue_host_ip

input_boolean:
  guest_mode:
    # This prevents certain automations from executing.
    # e.g. turning everything off on our guests if we leave
    name: Guest mode
    initial: off
    icon: mdi:nature-people

# Show links to resources in log and frontend
# introduction:

# View all events in a logbook
logbook:

# Display a map on the frontend
map:

media_player:
  - platform: plex
  # - platform: samsungtv
  #   host: !secret samsung_tv_host_ip
  #   mac: !secret samsung_tv_mac_address
  #   port: 8001
  #   name: Living Room TV
  - platform: sonos

# Presence / CloudMQTT / Owntracks
mqtt:
  broker: m12.cloudmqtt.com
  port: 27170
  username: !secret mqtt_username
  password: !secret mqtt_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_secret

notify:
  - name: facebook
    platform: facebook
    page_access_token: !secret facebook_token
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

nuheat:
  username: !secret nuheat_username
  password: !secret nuheat_password
  devices: !secret nuheat_thermostat

# Make sure to purge the history to keep the DB reasonably sized.
recorder:
  purge_interval: 1
  purge_keep_days: 14
  exclude:
    domains:
      - automation

ring:
  username: !secret ring_username
  password: !secret ring_password

scene: !include_dir_merge_list scenes

script: !include_dir_merge_named scripts

sensor:
  - platform: arlo
    monitored_conditions:
      - battery_level
      - captured_today
      - last_capture
      - total_cameras
      - signal_strength
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - icon
      - apparent_temperature
      - apparent_temperature_max
      - apparent_temperature_min
      - cloud_cover
      - humidity
      - nearest_storm_distance
      - precip_intensity
      - precip_probability
      - temperature
      - temperature_max
      - temperature_min
      - wind_speed
      - wind_bearing
  - platform: ring
    monitored_conditions:
      - battery
      - last_activity
      - last_ding
      - last_motion
      - volume
  - platform: uptime

switch:
  - platform: template
    switches:
      party_christmas:
        friendly_name: Party christmas
        value_template: "{{ is_state('script.party_christmas', 'on') or is_state('script.restart_party_christmas', 'on') }}"
        turn_on:
          service: script.turn_on
          data:
            entity_id: script.party_christmas
        turn_off:
          service: script.turn_on
          data:
            entity_id: script.stop_party_christmas

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Check for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: tru

zwave:
  usb_path: /dev/cu.usbmodem431
  config_path: /usr/local/lib/python3.6/site-packages/python_openzwave/ozw_config
  #device_config:
  #  light.ge_45602_lamp_dimmer_module_level:
  #    # polling_intensity: 1
  #    refresh_value: true
  #    delay: 3

zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 150
  icon: mdi:home

zone 2:
  name: Gravitate
  latitude: !secret gravitate_latitude
  longitude: !secret gravitate_longitude
  icon: mdi:laptop
  radius: 100  # meters

zone 3:
  name: Carver
  latitude: !secret carver_latitude
  longitude: !secret carver_longitude
  icon: mdi:school
  radius: 200  # meters

zone 4:
  name: Stowe
  latitude: !secret stowe_latitude
  longitude: !secret stowe_longitude
  icon: mdi:school
  radius: 300  # meters

zone 5:
  name: YMCA
  latitude: !secret ymca_latitude
  longitude: !secret ymca_longitude
  radius: 120  # meters
  icon: mdi:dumbbell

zone 6:
  name: Yoga
  latitude: !secret powerlife_latitude
  longitude: !secret powerlife_longitude
  radius: 120
  icon: mdi:dumbbell
