version: '3'
services:
  web:
    image: homeassistant/home-assistant:2021.5.4
    environment:
      - TZ=America/Chicago
    volumes:
      - ./config:/config
    devices:
      - /dev/ttyACM0:/dev/ttyUSB0
    restart: always
    # network_mode: host
    ports:
      - '8124:8124'
    networks:
      - default

networks:
  default:
    external:
      name: dead-end-ranch

