version: '3'
services:
  web:
    image: homeassistant/home-assistant:latest
    environment:
      - TZ=America/Chicago
    volumes:
      - ./config:/config
    devices:
      - /dev/ttyACM0:/dev/ttyUSB0
    restart: always
    network_mode: host

