# party_christmas:
#   sequence:
#     - service: light.turn_on
#       data:
#         entity_id: light.cabinet_accents
#         rgb_color: [255,43,21]  # red
#         brightness: 178
#         transition: 3
#     - service: light.turn_on
#       data:
#         entity_id: light.fridge_accents
#         rgb_color: [81,255,79]  # green
#         brightness: 178
#         transition: 3
#     - delay: 00:10:00  # minute
#     - service: light.turn_on
#       data:
#         entity_id: light.cabinet_accents
#         rgb_color: [81,255,79]
#         brightness: 178
#         transition: 3
#     - service: light.turn_on
#       data:
#         entity_id: light.fridge_accents
#         rgb_color: [255,43,21]
#         brightness: 178
#         transition: 3
#     - service: script.turn_on
#       data:
#         entity_id: script.restart_party_christmas
# 
# restart_party_christmas:
#   sequence:
#     - delay: 00:10:00  # minute
#     - service: script.turn_on
#       data:
#         entity_id: script.party_christmas
# 
# stop_party_christmas:
#   sequence:
#     - service: script.turn_off
#       data:
#         entity_id: script.party_christmas
#     - service: script.turn_off
#       data:
#         entity_id: script.restart_party_christmas
# 
# christmas_kitchen:
#   alias: Christmas kitchen
#   sequence:
#     - service: scene.turn_on
#       entity_id:
#         - scene.christmas_kitchen_accents
#         - scene.relaxed_island
# 
# christmas_great_room:
#   sequence:
#     - service: script.turn_on
#       data:
#         entity_id: script.christmas_kitchen
#     - service: light.turn_on
#       data:
#         entity_id:
#           - light.lamp_dimmer_one_level  # Christmas tree
#           - light.lamp_dimmer_two_level  # TV Christmas lights
#         brightness_pct: 100
#         transition: 3

