turn_off_house:
  sequence:
  - service: light.turn_off
    entity_id: group.all_lights
  - service: switch.turn_off
    entity_id: group.all_switches
  - service: media_player.turn_off
    entity_id: group.sonos

turn_off_office:
  sequence:
    - service: light.turn_off
      data:
        entity_id: light.office  # Hue group
    - service: light.turn_off
      data:
        entity_id: light.office_desk_lamp  # Blinky
    - service: switch.turn_off
      entity_id: switch.office_ge_12721_switch  # Miffy

# Leave Miffy on
turn_off_office_evening:
  sequence:
    - service: light.turn_off
      data:
        entity_id: light.office  # Hue group
    - service: light.turn_off
      data:
        entity_id: light.office_desk_lamp  # Blinky

# Kitchen
ambient_kitchen:
  alias: Ambient kitchen
  sequence:
    - service: automation.turn_off
      data:
        entity_id: group.dining_room_motion
    - service: light.turn_off
      data:
        entity_id:
          - light.island
          - light.kitchen_cooking_lights
    - service: scene.turn_on
      entity_id:
        - scene.blue_kitchen_accents
        - scene.fireplace_accent
    - service: light.turn_on
      data:
        entity_id: light.sink_lights
        brightness_pct: 50
        color_temp: 325

bright_kitchen:
  alias: Bright kitchen
  sequence:
    - service: scene.turn_on
      entity_id:
        - scene.blue_kitchen_accents
        - scene.bright_island
        - scene.bright_sink
        - scene.fireplace_accent
    - service: light.turn_on
      data:
        entity_id: light.kitchen_cooking_lights
        brightness_pct: 100

relaxed_kitchen:
  alias: Relaxed kitchen
  sequence:
    - service: scene.turn_on
      entity_id:
        - scene.blue_kitchen_accents
        - scene.relaxed_island
        - scene.relaxed_sink
        - scene.fireplace_accent
    - service: light.turn_off
      data:
        entity_id: light.kitchen_cooking_lights

# Living room
ambient_living_room:
  alias: Ambient living room
  sequence:
    - service: light.turn_off
      data:
        entity_id: light.living_room_ceiling_lamp
    - service: scene.turn_on
      entity_id:
        - scene.red_tree_accent
        - scene.red_turntable
    - service: switch.turn_off
      entity_id: switch.couch_ge_12721_switch

relaxed_living_room:
  alias: Relaxed living room
  sequence:
    - service: scene.turn_on
      entity_id:
        - scene.red_tree_accent
        - scene.red_turntable
    - service: light.turn_on
      data:
        entity_id:
          - light.living_room_ceiling_lamp
          - light.front_foyer_foyer_light
        brightness_pct: 30
    - service: switch.turn_on
      entity_id: switch.couch_ge_12721_switch

# Great room
ambient_great_room:
  alias: Amibent great room
  sequence:
    - service: automation.turn_off
      data:
        entity_id: group.dining_room_motion
    - service: script.turn_on
      entity_id:
        - script.ambient_kitchen
        - script.ambient_living_room
    - service: scene.turn_on
      entity_id: scene.ambient_stairwell
    - service: light.turn_off
      data:
        entity_id:
          - light.lounge_lounge_lights
          - light.front_foyer_foyer_light
          - light.dining_room_table_lights

bright_great_room:
  alias: Bright great room
  sequence:
    - service: scene.turn_on
      entity_id:
        - scene.bright_dining_room
        - scene.bright_living_room
        - scene.bright_lounge
        - scene.bright_stairwell
    - service: script.turn_on
      entity_id: script.bright_kitchen

orange_great_room:
  alias: Orange great room
  sequence:
    - service: scene.turn_on
      entity_id:
        - scene.orange_kitchen_accents
        - scene.orange_turntable
        - scene.orange_office

relaxed_great_room:
  alias: Relaxed great room
  sequence:
    - service: scene.turn_on
      entity_id:
        - scene.relaxed_dining_room
        - scene.relaxed_lounge
        - scene.relaxed_stairwell
    - service: script.turn_on
      entity_id:
        - script.relaxed_kitchen
        - script.relaxed_living_room

# Upstairs
bright_upstairs:
  alias: Bright upstairs
  sequence:
    - service: script.turn_on
      entity_id:
        - script.bright_great_room
    - service: scene.turn_on
      entity_id:
        - scene.bright_bedroom
        - scene.bright_office

relaxed_upstairs:
  alias: Relaxed upstairs
  sequence:
    - service: script.turn_on
      entity_id: script.relaxed_great_room
    - service: scene.turn_on
      entity_id:
        - scene.relaxed_bedroom
        - scene.relaxed_office

prepare_bedtime_lights:
  sequence:
  - condition: and
    conditions:
    - condition: state
      entity_id: group.family
      state: home
    - condition: or
      conditions:
      - condition: time
        after: '20:59:00'
      - condition: sun
        before: sunrise
  - service: scene.turn_on
    entity_id: scene.relaxed_bedroom
  - service: notify.derek
    data:
      title: Lights
      message: Bedtime lights activated

bedtime:
  sequence:
  - service: scene.turn_on
    entity_id: scene.relaxed_bedroom
  - delay: 00:01:00  # minute
  - service: homeassistant.turn_off
    entity_id: group.non_bedroom_lights

