turn_off_house:
  sequence:
  - service: light.turn_off
    entity_id: group.all_lights
  - service: switch.turn_off
    entity_id: group.all_switches
  - service: media_player.turn_off
    entity_id: group.sonos

prepare_bedtime_lights:
  sequence:
  - condition: and
    conditions:
    - condition: state
      entity_id: group.family
      state: home
    - condition: or
      conditions:
      - condition: time
        after: '20:59:00'
      - condition: sun
        before: sunrise
  - service: scene.turn_on
    entity_id: scene.relaxed_bedroom
  - service: notify.pushbullet
    data:
      title: Lights
      message: Bedtime lights activated

bedtime:
  sequence:
  - service: scene.turn_on
    entity_id: scene.relaxed_bedroom
  - delay: 00:01:00  # minute
  - service: homeassistant.turn_off
    entity_id: group.non_bedroom_lights
