- platform: template
  switches:
    party_christmas:
      friendly_name: Party christmas
      value_template: "{{ is_state('script.party_christmas', 'on') or is_state('script.restart_party_christmas', 'on') }}"
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.party_christmas
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.stop_party_christmas

    white_noise:
      friendly_name: White noise
      value_template: "{{ is_state('media_player.bedroom_speaker', 'playing') }}"
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.play_white_noise
      turn_off:
        service: media_player.media_stop
        data:
          entity_id: media_player.bedroom_speaker
