- name: Bedroom reading
  entities:
    light.master_bedroom:  # Light group from Hue (operates all lights at once)
      state: on
      brightness: 252  # 99%
      rgb_color: [255,210,129]

- name: Bedtime
  entities:
    group.non_bedroom_lights: off
    light.exterior_front_porch: off

- name: Bedtime early
  entities:
    light.master_bedroom: off
    light.front_foyer_foyer_light:
      state: on
      brightness: 26  # 10%
    light.exterior_front_porch:
      state: off

- name: Bedtime emergency
  entities:
    group.non_bedroom_lights: on
    light.exterior_front_porch: on

- name: Bright bedroom
  entities:
    light.master_bedroom:
      state: on
      brightness: 255
      color_temp:  312 # 3200k

- name: Dim bedroom
  entities:
    light.master_bedroom:
      state: on
      brightness: 1
      rgb_color: [255,161,40]

- name: Relaxed bedroom
  entities:
    light.master_bedroom:
      state: on
      brightness: 129  # 50%
      color_temp: 446
