# TODO: on weekdays, move from bright to dim after 9pm
- name: Movie time
  entities:
    light.island: off
    light.lounge_lounge_lights: off
    light.dining_room_table_lights: off
    switch.couch_ge_12721_switch: off
    light.living_room_ceiling_lamp:
      state: on
      brightness_pct: 10
    light.cabinet_accents:
      state: on
      rgb_color: [255,63,0]
      brightness_pct: 70
    light.fireplace_accent:
      state: on
      rgb_color: [255,63,0]
      brightness_pct: 70
    light.fridge_accents:
      state: on
      rgb_color: [255,63,0]
      brightness_pct: 70
    light.front_foyer_foyer_light:
      state: on
      brightness_pct: 10
    light.stairwell:
      state: on
      rgb_color: [255,63,0]  # red
      brightness_pct: 5
    light.turntable:
      state: on
      rgb_color: [255,63,0]  # red
      brightness_pct: 5

