# TODO: on weekdays, move from bright to dim after 9pm

- name: Bright great room
  entities:
    scene.bright_dining_room:
      state: on
    scene.bright_kitchen:
      state: on
    scene.bright_living_room:
      state: on
    scene.bright_lounge:
      state: on
    scene.bright_stairwell:
      state: on

- name: Relaxed great room
  entities:
    scene.relaxed_dining_room:
      state: on
    scene.relaxed_kitchen:
      state: on
    scene.relaxed_living_room:
      state: on
    light.lounge_lights: off
    scene.relaxed_stairwell:
      state: on

- name: Bright upstairs
  entities:
    scene.bright_great_room:
      state: on
    scene.bright_bedroom:
      state: on
    scene.bright_office:
      state: on

- name: Relaxed upstairs
  entities:
    scene.relaxed_great_room:
      state: on
    scene.relaxed_bedroom:
      state: on
    scene.relaxed_office:
      state: on

- name: Movie time
  entities:
    group.island_lights: off
    light.lounge_lights: off
    light.table_lights: off
    switch.couch_ge_12721_switch: off
    light.ceiling_lamp:
      state: on
      brightness_pct: 10
    light.cabinets:
      state: on
      rgb_color: [255,63,0]
      brightness_pct: 70
    light.fridge_lights:
      state: on
      rgb_color: [255,63,0]
      brightness_pct: 70
    light.foyer_light:
      state: on
      brightness_pct: 10
    group.stairwell:
      state: on
      rgb_color: [255,63,0]  # red
      brightness_pct: 5
    group.turntable_lights:
      state: on
      rgb_color: [255,63,0]  # red
      brightness_pct: 5
