- name: Bright living room
  entities:
    light.living_room_ceiling_lamp:
      state: on
      brightness: 255  # 100%
    light.turntable:
      state: on
      brightness: 255  # 100%
      color_temp: 312  # 3200k
    switch.couch_ge_12721_switch:
      state: on

- name: Orange turntable
  entities:
    light.turntable:
      state: on
      rgb_color: [255, 95, 0]
      brightness: 255  # 100%

- name: Red turntable
  entities:
    light.turntable:
      state: on
      rgb_color: [255,63,0]
      brightness: 179  # 70%

- name: Red tree accent
  entities:
    light.tree_accent:
      state: on
      rgb_color: [255,63,0]
      brightness: 255  # 100%
