- name: Ambient office
  entities:
    light.office_lamp: off
    light.big_office_lamp: off
    light.office_desk_lamp:  # Blinky
      state: on
      brightness_pct: 30
    switch.office_ge_12721_switch:  # Miffy
      state: on

- name: Bright office
  entities:
    light.office_lamp:
      state: on
      brightness_pct: 100
      color_temp: 325  # matches osrams at 100% brightness
    light.big_office_lamp:
      state: on
      brightness_pct: 100
      color_temp: 325  # matches osrams at 100% brightness
    light.office_desk_lamp:  # Blinky
      state: on
      brightness_pct: 30
    switch.office_ge_12721_switch:  # Miffy
      state: on

- name: Energized office
  entities:
    light.office_lamp:
      state: on
      brightness_pct: 100
      color_temp: 156
    light.big_office_lamp:
      state: on
      brightness_pct: 100
      color_temp: 156

- name: Orange office
  entities:
    light.office_lamp:
      state: on
      brightness_pct: 100
      rgb_color: [255, 95, 0]
    light.office_desk_lamp:  # Blinky
      state: on
      brightness_pct: 30
    switch.office_ge_12721_switch:  # Miffy
      state: on

- name: Office accents
  entities:
    light.office_desk_lamp:  # Blinky
      state: on
      brightness_pct: 30
    switch.office_ge_12721_switch:  # Miffy
      state: on

- name: Relaxed office
  entities:
    light.office_lamp:
      state: on
      brightness_pct: 50
      color_temp: 446
    light.big_office_lamp:
      state: on
      brightness_pct: 50
      color_temp: 446
    light.office_desk_lamp:  # Blinky
      state: on
      brightness_pct: 30
    switch.office_ge_12721_switch:  # Miffy
      state: on

