- name: Ambient office
  entities:
    group.office_motion: off
    light.office_lamp: off
    light.big_office_lamp: off
    light.office_desk_lamp:  # Blinky
      state: on
      brightness: 77  # 30%
    switch.office_ge_12721_switch:  # Miffy
      state: on

- name: Bright office
  entities:
    light.office_lamp:
      state: on
      brightness: 255  # 100%
      color_temp: 312  # 3200k
    light.big_office_lamp:
      state: on
      brightness: 255  # 100%
      color_temp: 312  # 3200k
    light.office_desk_lamp:  # Blinky
      state: on
      brightness: 77  # 30%
    switch.office_ge_12721_switch:  # Miffy
      state: on

- name: Energized office
  entities:
    light.office_lamp:
      state: on
      brightness: 255  # 100%
      color_temp: 156
    light.big_office_lamp:
      state: on
      brightness: 255  # 100%
      color_temp: 156

- name: Orange office
  entities:
    light.office_lamp:
      state: on
      brightness: 255  # 100%
      rgb_color: [255, 95, 0]
    light.office_desk_lamp:  # Blinky
      state: on
      brightness: 77  # 30%
    switch.office_ge_12721_switch:  # Miffy
      state: on

- name: Office accents
  entities:
    light.office_desk_lamp:  # Blinky
      state: on
      brightness: 77  # 30%
    switch.office_ge_12721_switch:  # Miffy
      state: on

- name: Relaxed office
  entities:
    light.office_lamp:
      state: on
      brightness: 129  # 50%
      color_temp: 446
    light.big_office_lamp:
      state: on
      brightness: 129  # 50%
      color_temp: 446
    light.office_desk_lamp:  # Blinky
      state: on
      brightness: 77  # 30%
    switch.office_ge_12721_switch:  # Miffy
      state: on

