#- id: arm_arlo_when_leaving
#  alias: Arm Arlo cameras when leaving
#  trigger:
#    platform: state
#    entity_id: group.family
#    from: home
#    to: not_home
#  condition:
#    condition: state
#    entity_id: input_boolean.guest_mode
#    state: 'off'
#  action:
#    - service: alarm_control_panel.alarm_arm_away
#      entity_id: alarm_control_panel.living_room

#- id: disarm_arlo_when_arriving
#  alias: Set Arlo cameras to Home mode when arriving
#  trigger:
#    platform: state
#    entity_id: group.family
#    from: not_home
#    to: home
#  action:
#    - service: alarm_control_panel.alarm_arm_home
#      entity_id: alarm_control_panel.living_room

- id: motion_in_garage
  alias: Motion in garage
  trigger:
    platform: state
    entity_id: binary_sensor.garage_camera_motion_detected
    to: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.garage_camera
        filename: /config/www/garage.jpg
    - service: notify.derek
      data:
        title: Motion
        message: Motion in the garage
        data:
          attachment:
            content-type: jpg
            hide-thumbnail: false
          entity_id: camera.garage_camera
          push:
            badge: 0
            category: camera

- alias: Send camera event notification
  trigger:
    platform: mqtt
    topic: frigate/events
  condition:
    #- "{{ trigger.payload_json['after']['entered_zones']|length > 0 }}"
    - "{{ trigger.payload_json['type'] == 'new' }}"
  action:
    - service: notify.derek
      data_template:
        message: A {{trigger.payload_json["after"]["label"]}} ({{ (trigger.payload_json["after"]["top_score"] | float * 100) | round(0) }}%) was detected on the {{trigger.payload_json["after"]["camera"]}} camera.
        data:
          attachment:
            content-type: jpg
            hide-thumbnail: false
            url: '{{states("input_text.public_domain")}}/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg'
          push:
            category: camera
          url: 
            _: /lovelace/cameras
            VIEW_VIDEO: '{{states("input_text.public_domain")}}/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/{{trigger.payload_json["after"]["camera"]}}/clip.mp4'
            VIEW_SNAPSHOT: '{{states("input_text.public_domain")}}/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg'
          apns_headers:
            apns-collapse-id: motion-{{trigger.payload_json["after"]["id"]}}
          action_data:
            video_url: '{{states("input_text.public_domain")}}/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/{{trigger.payload_json["after"]["camera"]}}/clip.mp4'
            snapshot_url: '{{states("input_text.public_domain")}}/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg'

