- id: evening_christmas_lights
  alias: Turn on Christmas lights in the evening
  trigger:
    platform: sun
    event: sunset
  condition:
    - condition: state
      entity_id: binary_sensor.christmas_time
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.christmas_lights

