- id: floor_off_when_leaving
  alias: Turn off heated floor when leaving
  trigger:
    platform: state
    entity_id: group.family
    from: home
    to: not_home
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.master_bath
      temperature: 50

- id: floor_resume_when_arriving
  alias: Resume heated floor schedule when arriving
  trigger:
    platform: state
    entity_id: group.family
    from: home
    to: not_home
  action:
    service: climate.nuheat_resume_program
