- id: check_doors_at_bedtime
  alias: Check whether doors are open when the bedroom lights turn off at night
  trigger:
    platform: state
    entity_id: group.bedroom
    to: 'off'
  condition:
    condition: time
    after: '21:00:00'
  action:
    - service: script.check_garage_door
    - service: script.check_mud_room_door

- id: garage_door_left_open
  alias: Garage door left open
  trigger:
    platform: state
    entity_id: cover.garage_door_opener
    to: open
    for:
      minutes: 7
  action:
    service: script.check_garage_door

- id: mud_room_door_open
  alias: Mud room door open
  trigger:
    platform: state
    entity_id: binary_sensor.mud_room_door
    to: 'on'
  condition:
    - condition: state
      entity_id: group.family
      state: not_home
  action:
    service: script.check_mud_room_door

- id: mud_room_door_left_open
  alias: Mud room door left open
  trigger:
    platform: state
    entity_id: binary_sensor.mud_room_door
    to: 'on'
    for:
      minutes: 5
  action:
    service: script.check_mud_room_door

