# To expose z-wave outlets to homekit, we must wait for the network to be ready

- alias: Start HomeKit
  trigger:
    - platform: event
      event_type: zwave.network_ready
    - platform: event
      event_type: zwave.network_complete
    - platform: event
      event_type: zwave.network_complete_some_dead
  action:
    - service: homekit.start