- id: music_off_when_leaving
  alias: Turn off music when leaving
  trigger:
    platform: state
    entity_id: group.family
    from: home
    to: not_home
  condition:
    condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
    service: media_player.turn_off
    entity_id: group.sonos

- id: tv_off_when_leaving
  alias: Turn off TV when leaving
  trigger:
    platform: state
    entity_id: group.family
    from: home
    to: not_home
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'off'
        - condition: state
          entity_id: media_player.living_room_tv
          state: 'on'
  action:
    service: media_player.turn_off
    entity_id: media_player.living_room_tv

- id: turntable_lights_on_when_playing
  alias: Turn on turntable lights when playing
  trigger:
    platform: state
    entity_id: media_player.turntable
    to: playing
  action:
    service: scene.turn_on
    entity_id: scene.red_turntable
