- id: enable_motion_detection
  alias: Enable motion detection
  trigger:
    - platform: time
      at: '9:00:00'
  action:
    - service: automation.turn_on
      entity_id:
        - group.dining_room_motion
        - group.office_motion
        - group.rec_room_motion

# DINING ROOM

- id: dining_room_motion_detected_day
  alias: Dining room motion detected (when dark)
  trigger:
    platform: state
    entity_id: binary_sensor.aeon_labs_zw100_multisensor_6_sensor
    to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.dark_dining_room
      state: 'on'
    - condition: time
      after: '9:59:59'
      before: '22:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.bright_dining_room

- id: dining_room_motion_detected_night
  alias: Dining room motion detected at night
  trigger:
    platform: state
    entity_id: binary_sensor.aeon_labs_zw100_multisensor_6_sensor
    to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.dark_dining_room
      state: 'on'
    - condition: time
      after: '21:59:59'
      before: '10:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.relaxed_dining_room

- id: dining_room_motion_detected
  alias: Dining room motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.aeon_labs_zw100_multisensor_6_sensor
    to: 'on'
  action:
    - service: script.turn_off
      data:
        entity_id: script.dining_room_motion_clear

- id: dining_room_motion_clear
  alias: Dining room motion clear
  trigger:
    platform: state
    entity_id: binary_sensor.aeon_labs_zw100_multisensor_6_sensor
    to: 'off'
  action:
    service: script.dining_room_motion_clear

# OFFICE

- id: office_motion_detected_dark_day
  alias: Office motion detected (when dark)
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.dark_office
      state: 'on'
    - condition: time
      after: '9:59:59'
      before: '22:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.bright_office

- id: office_motion_detected_night
  alias: Office motion detected at night
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.dark_office
      state: 'on'
    - condition: time
      after: '21:59:59'
      before: '10:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.relaxed_office

- id: office_motion_detected
  alias: Office motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion
    to: 'on'
  action:
    - service: script.turn_off
      data:
        entity_id: script.office_motion_clear

- id: office_motion_clear
  alias: Office motion clear
  trigger:
    platform: state
    entity_id: binary_sensor.office_motion
    to: 'off'
  action:
    service: script.office_motion_clear

# REC ROOM

- id: rec_room_motion_detected_night
  alias: Rec room motion detected at night
  trigger:
    platform: state
    entity_id: binary_sensor.rec_room_motion
    to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.bright_rec_room

- id: rec_room_motion_detected
  alias: Rec room motion detected
  trigger:
    platform: state
    entity_id: binary_sensor.rec_room_motion
    to: 'on'
  action:
    - service: script.turn_off
      data:
        entity_id: script.rec_room_motion_clear

- id: rec_room_motion_clear
  alias: Rec room motion clear
  trigger:
    platform: state
    entity_id: binary_sensor.rec_room_motion
    to: 'off'
  action:
    service: script.rec_room_motion_clear

