- id: tell_garth_karis_home
  alias: Tell Garth Kari's Home
  trigger:
    - platform: state
      entity_id: person.kari_brooks
      to: home
  action:
#    - service: media_player.volume_set
#      entity_id: media_player.office_speaker
#      volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.office_speaker
      data:
        message: "Garth!"
    - delay: '1'
    - service: tts.google_say
      entity_id: media_player.office_speaker
      data:
        message: "Who's heere"
