- id: tell_dog_karis_home
  alias: Tell Dog Kari's Home
  trigger:
    - platform: state
      entity_id: person.kari_brooks
      from: not_home
      to: home
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.office_speaker
        message: "Benny! Who's here?"

