- platform: arlo
  monitored_conditions:
    - battery_level
    - captured_today
    - last_capture
    - total_cameras
    - signal_strength

- platform: ring
  monitored_conditions:
    - battery
    - last_activity
    - last_ding
    - last_motion
    - volume

- platform: template
  sensors:
    office_motion_battery:
      value_template: "{{ states.zwave.vision_zp3111_multisensor_4in1.attributes.battery_level }}"
      friendly_name: "Office motion sensor battery"
      entity_id: zwave.vision_zp3111_multisensor_4in1
      unit_of_measurement: '%'
