- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - icon
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - cloud_cover
    - humidity
    - nearest_storm_distance
    - precip_intensity
    - precip_probability
    - temperature
    - temperature_high
    - temperature_low
    - wind_speed
    - wind_bearing
- platform: uptime
