homeassistant:
  customize: !include customize.yaml

amcrest:
  - name: Garage camera
    host: !secret amcrest_garage_ip
    username: !secret amcrest_camera_user
    password: !secret amcrest_camera_password
    binary_sensors:
      - motion_detected
      - online
  - name: Driveway camera
    host: !secret amcrest_driveway_ip
    username: !secret amcrest_camera_user
    password: !secret amcrest_camera_password
    binary_sensors:
      - motion_detected
      - online

automation: !include automations.yaml

binary_sensor: !include_dir_merge_list binary_sensors

cloud:

# Enables configuration UI
config:

# Enables the frontend
frontend:

group: !include_dir_merge_named groups

# Enables support for tracking state changes over time
history:

http:
  server_port: 8124

homekit: !include homekit.yaml

input_boolean:

input_text:
  public_domain:
    initial: !secret public_domain

ios:
  push:
    categories:
      - name: Camera
        identifier: 'camera'
        actions:
          - identifier: 'VIEW_VIDEO'
            title: 'See video'
          - identifier: 'VIEW_SNAPSHOT'
            title: 'See snapshot'

mobile_app:

mqtt:
  broker: mosquitto

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_secret

notify:
  - name: derek
    platform: group
    services:
      - service: mobile_app_dereks_iphone
  - name: kari
    platform: group
    services:
      - service: mobile_app_kari_s_iphone
  - name: family
    platform: group
    services:
      - service: mobile_app_dereks_iphone
      - service: mobile_app_kari_s_iphone

scene: !include scenes.yaml

script: !include scripts.yaml

sensor: !include_dir_merge_list sensors

sun:

switch: !include_dir_merge_list switches

system_health:

tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    service_name: google_say
    base_url: !secret host_base_url 
