all_motion:
  name: All motion sensors
  entities:
    - group.dining_room_motion
    - group.office_motion
    - group.rec_room_motion

dining_room_motion:
  name: Dining room motion
  entities:
    - automation.dining_room_motion_clear
    - automation.dining_room_motion_detected
    - automation.dining_room_motion_detected_at_night
    - automation.dining_room_motion_detected_when_dark

office_motion:
  name: Office motion
  entities:
    - automation.office_motion_clear
    - automation.office_motion_detected
    - automation.office_motion_detected_when_dark
    - automation.office_motion_detected_at_night

rec_room_motion:
  name: Rec room motion
  entities:
    - automation.rec_room_motion_clear
    - automation.rec_room_motion_detected
    - automation.rec_room_motion_detected_at_night

