sonos:
  name: Sonos Speakers
  entities:
  - media_player.bathroom
  - media_player.bedroom
  - media_player.garage
  - media_player.kitchen
  - media_player.living_room
  - media_player.office
  - media_player.patio
  - media_player.rec_room
  - media_player.turntable
  - media_player.workshop

google_homes:
  name: Google homes
  entities:
    - media_player.bedroom_speaker
    - media_player.kitchen_home
