- id: evening_lights
  alias: Turn on lights in the evening
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  - entity_id: group.family
    platform: state
    to: home
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: group.family
      state: home
    - after: sunset
      after_offset: -01:00:00
      condition: sun
    - after: '16:00:00'
      before: '22:00:00'
      condition: time
  action:
  - service: scene.turn_on
    entity_id: scene.kitchen_blues, scene.red_turntable
  - service: light.turn_on
    entity_id: group.stairwell
    data:
      brightness: 144
      profile: relax
  - service: switch.turn_on
    entity_id: switch.couch_ge_12721_switch, switch.office_ge_12721_switch
  - service: notify.facebook
    data:
      message: Evening lights activated
      target: !secret notify_phone_number

- id: bedtime_lights
  alias: Turn on bedroom lights before bed
  trigger:
  - platform: time
    at: '21:00:00'
  action:
  - service: scene.turn_on
    entity_id: scene.relaxed_bedroom
  - service: notify.facebook
    data:
      message: Bedtime lights activated
      target: !secret notify_phone_number 
