# My Monoprice Z-wave motion sensors don't report motion as binary. This is a
# hack to create binary sensors off of the "alarm_level" reading.

- platform: template
  sensors:
    dark_dining_room:
      friendly_name: Dark dining room
      value_template: >-
        {%- set lux = states('sensor.aeon_labs_zw100_multisensor_6_luminance') | float %}
        {{ is_state('binary_sensor.daylight', 'off') or lux < 20 }}
    dark_office:
      friendly_name: Dark office
      value_template: >-
        {%- set lux = states('sensor.vision_zp3111_multisensor_4in1_luminance') | float %}
        {{ is_state('binary_sensor.daylight', 'off') or lux < 40 }}
    dark_rec_room:
      friendly_name: Dark rec room
      value_template: "{{ is_state('binary_sensor.daylight', 'off') }}"
    daylight:
      friendly_name: Daylight
      value_template: "{{ state_attr('sun.sun','elevation') | float >= 12 }}"
    golden_hour:
      friendly_name: Golden hour
      value_template: >-
        {%- set elevation = state_attr('sun.sun','elevation') | float %}
        {{ elevation < 12 and elevation > 0 }}
    house_occupied:
      device_class: occupancy
      value_template: "{{ is_state('group.family', 'home') or is_state('input_boolean.guest_mode', 'on') }}"
    office_motion:
      device_class: motion
      entity_id: sensor.vision_zp3111_multisensor_4in1_alarm_level
      friendly_name: 'Office motion'
      value_template: "{{ is_state('sensor.vision_zp3111_multisensor_4in1_alarm_level', '255') }}"
    rec_room_motion:
      device_class: motion
      entity_id: sensor.vision_zp3102_pir_motion_sensor_alarm_level
      friendly_name: 'Rec room motion'
      value_template: "{{ is_state('sensor.vision_zp3102_pir_motion_sensor_alarm_level', '255') }}"
